// Linter and compiler settings that enforce the same thing as a catalog rule. Used by
// `groundrule scan` to propose adopting rules a team already enforces (B2). Every ID here
// must exist in the catalog; test/mappings.test.ts checks.
import type { ToolMapping } from "@groundrule/core";

export const TOOL_MAPPING: ToolMapping = {
  eslint: {
    "no-console": "TS-001",
    "no-eval": "TS-003",
    "no-implied-eval": "TS-003",
    "no-new-func": "TS-003",
    "@typescript-eslint/no-implied-eval": "TS-003",
    "@typescript-eslint/ban-ts-comment": "TS-004",
    "@typescript-eslint/prefer-ts-expect-error": "TS-004",
    "@typescript-eslint/no-explicit-any": "TS-005",
    "@typescript-eslint/no-floating-promises": "TS-006",
    "@typescript-eslint/no-misused-promises": "TS-006",
    "@typescript-eslint/no-non-null-assertion": "TS-008",
    "unicorn/prefer-node-protocol": "TS-009",
    "n/prefer-node-protocol": "TS-009",
    "no-process-exit": "TS-010",
    "n/no-process-exit": "TS-010",
    "unicorn/no-process-exit": "TS-010",
    "no-buffer-constructor": "TS-011",
    "n/no-deprecated-api": "TS-011",
    "no-sync": "TS-012",
    "n/no-sync": "TS-012",
    "@typescript-eslint/use-unknown-in-catch-callback-variable": "TS-013",
    "no-debugger": "TS-014",
    "react/no-danger": "REACT-001",
    "react/no-array-index-key": "REACT-002",
    "react/jsx-no-target-blank": "REACT-003",
    "react-hooks/rules-of-hooks": "REACT-005",
    "jsx-a11y/alt-text": "REACT-006",
    "jsx-a11y/click-events-have-key-events": "REACT-007",
    "jsx-a11y/no-static-element-interactions": "REACT-007",
    "react/prefer-stateless-function": "REACT-009",
    "jest/no-focused-tests": "TEST-001",
    "vitest/no-focused-tests": "TEST-001",
    "mocha/no-exclusive-tests": "TEST-001",
    "jest/no-disabled-tests": "TEST-002",
    "vitest/no-disabled-tests": "TEST-002",
    "playwright/no-wait-for-timeout": "TEST-005",
  },
  biome: {
    noConsole: "TS-001",
    noGlobalEval: "TS-003",
    noExplicitAny: "TS-005",
    noFloatingPromises: "TS-006",
    noNonNullAssertion: "TS-008",
    useNodejsImportProtocol: "TS-009",
    noProcessExit: "TS-010",
    noDebugger: "TS-014",
    noDangerouslySetInnerHtml: "REACT-001",
    noArrayIndexKey: "REACT-002",
    noBlankTarget: "REACT-003",
    useHookAtTopLevel: "REACT-005",
    useAltText: "REACT-006",
    useKeyWithClickEvents: "REACT-007",
    noStaticElementInteractions: "REACT-007",
    noFocusedTests: "TEST-001",
    noSkippedTests: "TEST-002",
  },
  ruff: {
    E722: "PY-001",
    B006: "PY-002",
    T201: "PY-003",
    S301: "PY-004",
    S506: "PY-005",
    S602: "PY-006",
    S604: "PY-006",
    S307: "PY-007",
    F403: "PY-008",
    S113: "PY-009",
    DTZ003: "PY-010",
    S201: "PY-011",
    S101: "PY-012",
    ANN201: "PY-013",
    G004: "PY-015",
    S311: "PY-016",
    S105: "SEC-012",
    S106: "SEC-012",
    S501: "SEC-004",
    S608: "SEC-015",
  },
  golangci: {
    errcheck: "GO-001",
    errorlint: "GO-002",
    contextcheck: "GO-004",
    noctx: "GO-006",
    gosec: "GO-009",
    forbidigo: "GO-010",
    bodyclose: "GO-012",
    sqlclosecheck: "GO-012",
  },
  checkstyle: {
    IllegalCatch: "JAVA-016",
    EmptyCatchBlock: "JAVA-016",
  },
  pmd: {
    SystemPrintln: "JAVA-002",
    AvoidPrintStackTrace: "JAVA-002",
    EmptyCatchBlock: "JAVA-016",
    AvoidCatchingGenericException: "JAVA-016",
  },
  tsconfig: {
    strict: "TS-007",
  },
};
