import { compareSeverity, type Example, type Standard } from "@groundrule/spec";

/** Standards that share a file scope are rendered together. */
export interface ScopeGroup {
  /** Stable key, e.g. "" for everywhere or "src/main/**|!src/main/gen/**". */
  key: string;
  paths: string[];
  exclude: string[];
  standards: Standard[];
}

export function sortStandards(standards: readonly Standard[]): Standard[] {
  return [...standards].sort(
    (a, b) =>
      compareSeverity(b.spec.severity, a.spec.severity) ||
      a.metadata.id.localeCompare(b.metadata.id),
  );
}

export function groupByScope(standards: readonly Standard[]): ScopeGroup[] {
  const groups = new Map<string, ScopeGroup>();
  for (const standard of sortStandards(standards)) {
    const paths = [...(standard.spec.scope.paths ?? [])].sort();
    const exclude = [...(standard.spec.scope.exclude ?? [])].sort();
    const key = paths.length ? [...paths, ...exclude.map((e) => `!${e}`)].join("|") : "";
    const group = groups.get(key) ?? { key, paths, exclude, standards: [] };
    group.standards.push(standard);
    groups.set(key, group);
  }
  // "Everywhere" first, then scoped groups alphabetically.
  return [...groups.values()].sort((a, b) =>
    a.key === "" ? -1 : b.key === "" ? 1 : a.key.localeCompare(b.key),
  );
}

export function scopeHeading(group: ScopeGroup): string {
  if (group.key === "") return "Everywhere";
  const paths = group.paths.map((p) => `\`${p}\``).join(", ");
  return group.exclude.length
    ? `${paths} (except ${group.exclude.map((e) => `\`${e}\``).join(", ")})`
    : paths;
}

/** File-name-safe slug for a scope group, stable across runs. */
export function scopeSlug(group: ScopeGroup): string {
  const base = group.paths
    .join("-")
    .replace(/\*\*?/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 40);
  let hash = 0;
  for (const ch of group.key) hash = (hash * 31 + ch.charCodeAt(0)) >>> 0;
  return `${base || "scoped"}-${hash.toString(36).slice(0, 5)}`;
}

/** One standard, written for a coding agent: short, imperative, with examples. */
export function renderStandard(standard: Standard): string {
  const { metadata, spec } = standard;
  const lines = [`- **${metadata.id}** ${metadata.title} · _${spec.severity}_`];
  const qualifiers = [...(spec.scope.languages ?? []), ...(spec.scope.frameworks ?? [])];
  const body = (spec.agent.summary ?? spec.requirement).replace(/\s+/g, " ").trim();
  lines.push(`  ${body}${qualifiers.length ? ` (${qualifiers.join(", ")})` : ""}`);
  const approved = spec.examples?.approved?.[0];
  const forbidden = spec.examples?.forbidden?.[0];
  if (approved) lines.push(...renderExample("Do", approved));
  if (forbidden) lines.push(...renderExample("Don't", forbidden));
  return lines.join("\n");
}

function renderExample(label: string, example: Example): string[] {
  const code = typeof example === "string" ? example : example.code;
  const language = typeof example === "string" ? "" : (example.language ?? "");
  const note = typeof example === "string" ? undefined : example.note;
  const trimmed = code.replace(/\s+$/, "");
  if (!trimmed.includes("\n")) return [`  - ${label}: \`${trimmed}\`${note ? ` (${note})` : ""}`];
  const indented = trimmed.split("\n").map((l) => `    ${l}`);
  return [
    `  - ${label}${note ? ` (${note})` : ""}:`,
    `    \`\`\`${language}`,
    ...indented,
    "    ```",
  ];
}

export const PREAMBLE = [
  "These are this repository's engineering ground rules. Follow them in every change.",
  "Before you finish a task, run `npx groundrule check` and fix what it reports.",
  "For the reasoning and examples behind a rule, run `npx groundrule explain <ID>`.",
].join("\n");

export const SOURCE_NOTE =
  "Generated by Groundrule from `.groundrule/`. Edit the standards there, then run `groundrule sync`.";

export function renderStandardsDocument(standards: readonly Standard[], headingLevel = 2): string {
  const h = "#".repeat(headingLevel);
  const out = [`${h} Engineering standards`, "", PREAMBLE, ""];
  for (const group of groupByScope(standards)) {
    out.push(`${h}# ${scopeHeading(group)}`, "");
    for (const standard of group.standards) out.push(renderStandard(standard), "");
  }
  return out.join("\n").trimEnd();
}
